
    <div ng-repeat="(field, msg) in feedback">
        <span class="ng-hide-remove" ng-class="'feedback-' + field" ng-cloak>{{msg}}</span>
    </div>
    <footer id="author" ng-cloak>
        <span class="pull-right">Powered by ESP &mdash; &copy; Embedthis Software 2015</span>
    </footer>
    <@
        if (meta.mode == 'debug' || meta.mode == 'dev') {
            renderScripts()
        } else {
            renderScripts(['!**.js'], 'all.min.js')
        }
    @>

